### ISSUE TITLE
Default value of override_galaxy_version handled incorrectly

### ISSUE THREAD

**Issue by vkrizan** [ansible-middleware/janus#29]
##### SUMMARY

If `override_galaxy_version` var is not specified for janus role then the default value of `None` isn't handled correctly.

Meta and defaults disagree:
```
# meta/argument_spec.yml
            override_galaxy_version:
                type: 'str'
                required: no
                default: None
                description: 'Set to override value of downstream version read from galaxy.yml'
```
```
# defaults/main.yml
override_galaxy_version:
```

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
2.15.0
```

##### COLLECTION VERSION

```
https://github.com/ansible-middleware/janus/commit/76f86596c6cdea3ffe1f3d75f779c517510caa7e
```

##### STEPS TO REPRODUCE

```yaml
---
- name: "Janus transformation process"
  hosts: localhost
  gather_facts: no
  collections:
    - middleware_automation.janus
  vars:
    galaxy:
      issues: https://issues.redhat.com/projects/EVNT/issues
      homepage: https://console.redhat.com/insights
    upstream_namespace: redhatinsights
    upstream_name: eda
    downstream_namespace: "redhat"
    downstream_name: insights_eda
    override_galaxy_version: None
    skip_setup: True

  tasks:
    - name: "Run Janus."
      ansible.builtin.include_role:
        name: middleware_automation.janus.janus
      tags: always
```

##### EXPECTED RESULTS

`override_galaxy_version` not required.

##### ACTUAL RESULTS

```
fatal: [localhost]: FAILED! => {"argument_errors": ["argument 'override_galaxy_version' is of type <class 'NoneType'> and we were unable to convert to str: 'None' is not a string and conversion is not allowed"], "argument_spec_data": {"downstream_name": {"description": "The name of the downstream collection to generate", "required": true, "type": "str"}, "downstream_namespace": {"default": "redhat", "description": "Name of the downstream namespace to generate the collection into", "type": "str"}, "downstream_placeholder_content": {"default": [], "description": "List of placeholder comments used to add/replace downstream documentation snippets. List of dict(placeholder:str,content:str)", "type": "list"}, "downstream_placeholder_delete": {"default": [], "description": "List of placeholder comments for removing upstream only documentation snippets", "type": "list"}, "downstream_projects_dir": {"default": "(HOME)/ansible-collections-eda/downstream", "description": "Directory where the downstream collection will be generated", "type": "str"}, "override_galaxy_version": {"default": "None", "description": "Set to override value of downstream version read from galaxy.yml", "required": false, "type": "str"}, "post_processors_replacements": {"default": [], "description": "List of { match, replace, file } dicts for post processing replacements. `match` and `replace` are regexes for string replacements while `file` is a regex matcher filtering filenames to post-process", "type": "list"}, "project_git_url": {"description": "If provided, the git url used to fetch the upstream project repository", "required": false, "type": "str"}, "project_git_version": {"description": "If provided along project_git_url, the branch to fetch the upstream project from", "required": false, "type": "str"}, "skip_setup": {"default": true, "description": "Whether to skip the pre-transformation setup phase", "type": "bool"}, "upstream_collection_name": {"default": "eda", "description": "Optional name of upstream collection", "required": false, "type": "str"}, "upstream_downstream_collections_map": {"default": [], "description": "List of dependency mappings {upstream_name, downstream_name} for renaming in tasks, galaxy.yml and requirements.yml", "type": "list"}, "upstream_name": {"description": "The prefix for roles in the upstream collection to transform", "required": true, "type": "str"}, "upstream_namespace": {"default": "middleware_automation", "description": "Name of the upstream namespace to transform", "type": "str"}, "upstream_organisation": {"default": "ansible-middleware", "description": "github.com organisation for upstream repositories", "type": "str"}, "upstream_projects_dir": {"default": "(HOME)/ansible-collections-eda/upstream", "description": "Directory where the upstream project is cloned from git", "type": "str"}, "workdir": {"default": "(HOME)/ansible-collections-eda", "description": "Working directory to run the transformation process onto", "type": "str"}}, "changed": false, "msg": "Validation of arguments failed:\nargument 'override_galaxy_version' is of type <class 'NoneType'> and we were unable to convert to str: 'None' is not a string and conversion is not allowed", "validate_args_context": {"argument_spec_name": "main", "name": "janus", "path": "(HOME)/.ansible/collections/ansible_collections/middleware_automation/janus/roles/janus", "type": "role"}}
```

Thanks.
